### ISSUE TITLE
Create a custom docker image for article database based on postgres image

### ISSUE THREAD

**Issue by Ukalus** [Ukalus/UkalusWebsite#3]
### Pretasks
- [ ] plan structure of database
- [ ] understand how to access database over socket 
- [ ] understand how to send requests to the database

### Tasks
- [ ] when starting container, create tables automatically 
- [ ] decide how to send requests (graohql / postgraphile ?) and integrate it into the backend
- [ ] implement access to the database in frontend 

### Sources
[how to create a prepopulated postgres database with docker(from the same creator of learnopengl.com)](https://dev.to/andre347/how-to-easily-create-a-postgres-database-in-docker-4moj)
